### ISSUE TITLE
Unable to clone the repo

### ISSUE THREAD

**Issue by tekpartner** [pkainulainen/test-with-spring#2]
Hi Petri,

I'm unable to clone the repo:

> $ git clone https://github.com/pkainulainen/test-with-spring.git
Cloning into 'test-with-spring'...
remote: Counting objects: 3280, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 3280 (delta 4), reused 0 (delta 0), pack-reused 3245
Receiving objects: 100% (3280/3280), 346.85 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1318/1318), done.
Checking connectivity... done.
error: unable to create file intermediate-package/writing-integ-tests-for-spring-web-apps/normal-controllers/spring-boot/src/integration-test/resources/com/testwithspring/intermediate/web/delete-task-should-delete-link-between-tag-and-deleted-task.xml: Filename too long
error: unable to create file intermediate-package/writing-integ-tests-for-spring-web-apps/normal-controllers/spring/src/integration-test/resources/com/testwithspring/intermediate/web/delete-task-should-delete-link-between-tag-and-deleted-task.xml: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by pkainulainen** [comment]
I am sorry that I didn't notice this issue sooner (Github doesn't seem to send me any notifications). I will investigate this tomorrow, but it seems that I have to rename that file.

**Comment by pkainulainen** [comment]
@tekpartner I took a quick look at this, and it seems that this might a Git client or OS specific issue. Could you provide the the name (and version) of Your Git client and OS that you are using.

**Comment by tekpartner** [comment]
Thanks for looking into this.

$ git --version
git version 2.9.0.windows.1

**Comment by tekpartner** [comment]
Tried to clone the repo using SourceTree (version 1.9.6.1), no luck:

![image](https://cloud.githubusercontent.com/assets/6240247/23035031/b506ecc0-f432-11e6-9069-ba1eb6d7b02f.png)

**Comment by pkainulainen** [comment]
The weird thing is that every article that mentions similar issues says that the file name cannot be longer than 260 characters, and the file names (technically paths) are way below that. Have you tried enabling the file path support of Git (it's disabled by default). You can enable it by running this command:

`git config --system core.longpaths true`

**Comment by tekpartner** [comment]
@pkainulainen - Yup, that did the trick !!

$ git clone https://github.com/pkainulainen/test-with-spring.git
Cloning into 'test-with-spring'...
remote: Counting objects: 5013, done.
remote: Compressing objects: 100% (548/548), done.
remote: Total 5013 (delta 340), reused 0 (delta 0), pack-reused 4355
Receiving objects: 100% (5013/5013), 564.01 KiB | 0 bytes/s, done.
Resolving deltas: 100% (2222/2222), done.
Checking connectivity... done.

**Comment by pkainulainen** [comment]
Cool. I will close this issue since you were able to clone the repo.
